### Request ###

chess_msgs/FullFEN fen
chess_msgs/ChessTime time

# This action can only be cancelled in analysis mode, but the engine can only offer draws and
# resigns with analysis mode off.
bool analysis_mode

---

### Result ###

chess_msgs/ChessMoveUCI move

---

### Feedback ###

chess_msgs/EngineInfo info