# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - cobot0_controller
    - cobot0_gripper_controller
    - cobot0_bias_controller

  cobot0_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - cobot0_joint_0
      - cobot0_joint_1
      - cobot0_joint_2
      - cobot0_joint_3
      - cobot0_joint_4
      - cobot0_joint_5
    action_ns: follow_joint_trajectory
    default: true
    execution_duration_monitoring: false
    
  cobot0_gripper_controller:
    type: GripperCommand
    action_ns: gripper_cmd
    default: true
    joints:
      - cobot0_gripper
    execution_duration_monitoring: false

  cobot0_bias_controller:
    type: JointGroupPositionController
    action_ns: bias_controller
    default: true
    joints:
      - cobot0_joint_0_bias
      - cobot0_joint_1_bias
      - cobot0_joint_2_bias
      - cobot0_joint_3_bias
      - cobot0_joint_4_bias