tof_piece_finder:
  depth_camera_base_topic:
    {
      type: string,
      default_value: "tof/depth/image_raw",
      description: "The base topic of the depth camera publisher that contains the image.",
    }
  ir_camera_base_topic:
    {
      type: string,
      default_value: "tof/ir/image_raw",
      description: "The base topic of the IR camera publisher that contains the image.",
    }

  binary_image_topic:
    {
      type: string,
      default_value: "tof/pieces/binary/image_raw",
      description: "The topic to publish the thresholded image to.",
    }

  annotated_image_topic:
    {
      type: string,
      default_value: "tof/pieces/annotated/image_raw",
      description: "The topic to publish the annotated image to.",
    }

  points_topic:
    {
      type: string,
      default_value: "tof/pieces/points",
      description:
        "The topic to publish points to. Each point represents the top-center of a piece on the
        board.",
    }

  camera_points_topic:
    {
      type: string,
      default_value: "tof/pieces/camera_points",
      description: "The topic to publish points to, measured as pixels in the image",
    }

  filter:
    max_height_difference:
      {
        type: double,
        default_value: 0.065,
        description:
          "The maximum distance from the top of the tallest piece that will be retained. This should
          be the distance from the top of the tallest piece to the top of the shortest piece, plus
          some buffer.",
      }
    gripper_mask_file:
      {
        type: string,
        default_value: "config/gripper_mask.png",
        description:
          "The path to the gripper mask file. This mask is used to ignore the gripper when finding
          the pieces.",
      }
    blur_size:
      {
        type: int,
        default_value: 15,
        description: "The size of the blur kernel to use when filtering the image.",
      }
    limits:
      max_distance:
        {
          type: double,
          default_value: 0.3,
          description: "The largest distance from the camera to consider.",
        }
      min_distance:
        {
          type: double,
          default_value: 0.09,
          description: "The smallest distance from the camera to consider.",
        }
      min_piece_size:
        {
          type: int,
          default_value: 64,
          description:
            "The minimum number of pixels that a piece must have to be considered a piece.",
        }
      max_piece_size:
        {
          type: int,
          default_value: 3000,
          description:
            "The maximum number of pixels that a piece must have to be considered a piece.",
        }
