# Information provided by the chess engine when it is thinking.

# https://backscattering.de/chess/uci/#engine-info

# uint8 TYPE_DEPTH = 0
# uint8 TYPE_SELDEPTH = 1
# uint8 TYPE_TIME = 2
# uint8 TYPE_NODES = 3
# uint8 TYPE_PV = 4
# uint8 TYPE_MULTIPV = 5
# uint8 TYPE_SCORE = 6
# uint8 TYPE_CURRMOVE = 7
# uint8 TYPE_CURRMOVENUMBER = 8
# uint8 TYPE_HASHFULL = 9
# uint8 TYPE_NPS = 10
# uint8 TYPE_TBHITS = 11
# uint8 TYPE_SBHITS = 11
# uint8 TYPE_CPULOAD = 12
# uint8 TYPE_STRING = 13
# uint8 TYPE_REFUTATION = 14
# uint8 TYPE_CURRLINE = 15

# uint8 type

builtin_interfaces/Time timestamp
string type
string value