chess_player_params:

  cobot_ns:
    {
      type: string,
      default_value: "",
      description: "The namespace that this cobot's topics should use."
    }

  cobot_color:
    {
      type: string,
      default_value: "white",
      description: "The color that the COBOT is playing as. Either 'white' or 'black'.",
      validation: { one_of<>: [["white", "black"]] },
    }

  align_params:
    x_weight:
      {
        type: double,
        default_value: 0.01,
        description: "The weight that translates X error (in pixels) into X velocity",
      }
    y_weight:
      {
        type: double,
        default_value: 0.01,
        description: "The weight that translates Y error (in pixels) into Y velocity",
      }
    z_weight:
      {
        type: double,
        default_value: 50,
        description: "The weight that translates Z error (in meters) into Z velocity",
      }
    angular_weight:
      {
        type: double,
        default_value: 1.2,
        description: "The weight that translates angular error into angular velocity",
      }
    z_min:
      {
        type: double,
        default_value: -0.02,
        description: "The minimum Z value of the gripper when aligning (relative to hover_above_board)."
      }
    z_max:
      {
        type: double,
        default_value: 0.04,
        description: "The maximum Z value of the gripper when aligning (relative to hover_above_board)."
      }
    max_speed:
      {
        type: double,
        default_value: 0.1,
        description: "The maximum speed in each axis."
      }

  move_groups:
    cobot:
      {
        type: string,
        default_value: "cobot0",
        description: "The name of the move group to use for the COBOT arm.",
      }
    gripper:
      {
        type: string,
        default_value: "cobot0_gripper",
        description: "The name of the move group to use for the end effector.",
      }

  frames:
    chessboard:
      {
        type: string,
        default_value: "chessboard_frame",
        description: "The TF2 frame_id of the chessboard.",
      }

  measurements:
    chessboard_square_size:
      {
        type: double,
        default_value: 0.041375,
        description: "The size of each square on the chessboard in meters.",
      }
    hover_above_board:
      {
        type: double,
        default_value: 0.31,
        description: "The height to hover above the board in meters.",
      }
    min_grasp_height:
      {
        type: double,
        default_value: 0.21,
        description: "The minimum height for the gripper to go to in order to pick up a piece.",
      }
    pick_up_height:
      {
        type: double,
        default_value: 0.36,
        description: "The height to raise a piece to after picking it up.",
      }
    min_realign_dist:
      {
        type: double,
        default_value: 50,
        description: "The minimum distance away a chess piece must be in order to realign to it."
      }

  actions:
    find_best_move:
      {
        type: string,
        default_value: "chess/find_best_move",
        description: "The action to call to find the best move.",
      }

  sub_topics:
    tof_points:
      {
        type: string,
        default_value: "tof/pieces/camera_points",
        description:
          "The topic to subscribe to for the TOF's points. Each point represents a chess piece.",
      }
    game_state:
      {
        type: string,
        default_value: "chess/game_state",
        description: "The topic that the game state is published to.",
      }
    time:
      {
        type: string,
        default_value: "chess/time",
        description: "The topic that the game time is published to.",
      }
    enabled:
      {
        type: string,
        default_value: "enabled",
        description: "Topic that determines whether this COBOT is enabled.",
      }
    max_speed:
      {
        type: string,
        default_value: "max_speed",
        description: "Topic that determines the max speed of the COBOT.",
      }

  pub_topics:
    state:
      {
        type: string,
        default_value: "state",
        description: "The topic to publish the state of the COBOT to.",
      }
