# Default initial positions for two_cobots's ros2_control fake system

initial_positions:
  cobot0_gripper: 0
  cobot0_joint_0: 0
  cobot0_joint_1: 0
  cobot0_joint_2: 0
  cobot0_joint_3: 0
  cobot0_joint_4: 0
  cobot0_joint_5: 0
  cobot1_gripper: 0
  cobot1_joint_0: 0
  cobot1_joint_1: 0
  cobot1_joint_2: 0
  cobot1_joint_3: 0
  cobot1_joint_4: 0
  cobot1_joint_5: 0