# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  cobot0_gripper:
    has_velocity_limits: true
    max_velocity: 0.0087266462599716477
    has_acceleration_limits: false
    max_acceleration: 0
  cobot0_joint_0:
    has_velocity_limits: true
    max_velocity: 1.3962634015954636
    has_acceleration_limits: false
    max_acceleration: 0
  cobot0_joint_1:
    has_velocity_limits: true
    max_velocity: 1.0471975511965976
    has_acceleration_limits: false
    max_acceleration: 0
  cobot0_joint_2:
    has_velocity_limits: true
    max_velocity: 2.7925268031909272
    has_acceleration_limits: false
    max_acceleration: 0
  cobot0_joint_3:
    has_velocity_limits: true
    max_velocity: 4.1887902047863905
    has_acceleration_limits: false
    max_acceleration: 0
  cobot0_joint_4:
    has_velocity_limits: true
    max_velocity: 3.4906585039886591
    has_acceleration_limits: false
    max_acceleration: 0
  cobot0_joint_5:
    has_velocity_limits: true
    max_velocity: 26.179938779914941
    has_acceleration_limits: false
    max_acceleration: 0
  cobot1_gripper:
    has_velocity_limits: true
    max_velocity: 0.0087266462599716477
    has_acceleration_limits: false
    max_acceleration: 0
  cobot1_joint_0:
    has_velocity_limits: true
    max_velocity: 1.3962634015954636
    has_acceleration_limits: false
    max_acceleration: 0
  cobot1_joint_1:
    has_velocity_limits: true
    max_velocity: 1.0471975511965976
    has_acceleration_limits: false
    max_acceleration: 0
  cobot1_joint_2:
    has_velocity_limits: true
    max_velocity: 2.7925268031909272
    has_acceleration_limits: false
    max_acceleration: 0
  cobot1_joint_3:
    has_velocity_limits: true
    max_velocity: 4.1887902047863905
    has_acceleration_limits: false
    max_acceleration: 0
  cobot1_joint_4:
    has_velocity_limits: true
    max_velocity: 3.4906585039886591
    has_acceleration_limits: false
    max_acceleration: 0
  cobot1_joint_5:
    has_velocity_limits: true
    max_velocity: 26.179938779914941
    has_acceleration_limits: false
    max_acceleration: 0