# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - cobot0_controller
    - cobot1_controller
    - cobot0_gripper_controller
    - cobot1_gripper_controller

  cobot0_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - cobot0_joint_0
      - cobot0_joint_1
      - cobot0_joint_2
      - cobot0_joint_3
      - cobot0_joint_4
      - cobot0_joint_5
  cobot1_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - cobot1_joint_0
      - cobot1_joint_1
      - cobot1_joint_2
      - cobot1_joint_3
      - cobot1_joint_4
      - cobot1_joint_5
  cobot0_gripper_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - cobot0_gripper
  cobot1_gripper_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - cobot1_gripper