# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    cobot0_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    cobot1_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    cobot0_gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    cobot1_gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

cobot0_controller:
  ros__parameters:
    joints:
      - cobot0_joint_0
      - cobot0_joint_1
      - cobot0_joint_2
      - cobot0_joint_3
      - cobot0_joint_4
      - cobot0_joint_5
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
cobot1_controller:
  ros__parameters:
    joints:
      - cobot1_joint_0
      - cobot1_joint_1
      - cobot1_joint_2
      - cobot1_joint_3
      - cobot1_joint_4
      - cobot1_joint_5
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
cobot0_gripper_controller:
  ros__parameters:
    joint: cobot0_gripper
    command_interfaces:
      - position
    state_interfaces:
      - position
cobot1_gripper_controller:
  ros__parameters:
    joint: cobot1_gripper
    command_interfaces:
      - position
    state_interfaces:
      - position